services:
  - type: web
    name: chat-app-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
